name: flutter_advanced_canvas_editor
description: "A powerful Flutter canvas editor with Photoshop-style layers, freehand drawing, drag-and-drop components, undo/redo, and PNG export. Works on all platforms."
version: 2.1.0
homepage: https://github.com/Dojibery/flutter-advanced-canvas-editor

environment:
  sdk: '>=3.3.3 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

repository: https://github.com/Dojibery/flutter-advanced-canvas-editor
issue_tracker: https://github.com/Dojibery/flutter-advanced-canvas-editor/issues
